application: vaskenmusic
version: 1
runtime: java

handlers:
- url: /vaskenmusicserver
  servlet: com.vasken.music.server.VaskenMusicServerServlet

- url: /tasks/cleanupJob
  servlet: com.vasken.music.server.CronServlet
  login: admin

- url: /tasks/catalogUpdater
  servlet: com.vasken.music.server.CatalogUpdaterServlet
  login: admin
  
- url: /tasks/catalogUpdateJob
  servlet: com.vasken.music.server.CatalogCronServlet
  login: admin
  
welcome_files:
  - index.html
  
