package com.vasken.comics;

import java.util.ArrayList;
import java.util.Collections;
import java.util.concurrent.Callable;

import android.content.Context;

import com.vasken.comics.Downloaders.ComicsKingdomDownloader;
import com.vasken.comics.Downloaders.Downloader;
import com.vasken.comics.Downloaders.SharingMachineDownloader;
import com.vasken.comics.R;

public class ComicList {
	
	static ArrayList<ComicInfo> comics = new ArrayList<ComicInfo>();

	static ArrayList<ComicInfo> comicList() { return comics; }
	
	static void init(Context context) {
		comics.add(new ComicInfo(context, R.raw.achewood));
		comics.add(new ComicInfo(context, R.raw.alessonislearned));
		comics.add(new ComicInfo(context, R.raw.amazingsuperpowers));
		comics.add(new ComicInfo(context, R.raw.asofterworld));
		comics.add(new ComicInfo(context, R.raw.awkwardzombie));
		comics.add(new ComicInfo(context, R.raw.bookofbiff));
		comics.add(new ComicInfo(context, R.raw.buttersafe));
		comics.add(new ComicInfo(context, R.raw.capesnbabes));
		comics.add(new ComicInfo(context, R.raw.ctrlaltdel));
		comics.add(new ComicInfo(context, R.raw.ctrlaltdelsillies));
		comics.add(new ComicInfo(context, R.raw.cyanideandhappiness));
		comics.add(new ComicInfo(context, R.raw.dieselsweeties));
		comics.add(new ComicInfo(context, R.raw.dilbert));
		comics.add(new ComicInfo(context, R.raw.dinosaurcomics));
		comics.add(new ComicInfo(context, R.raw.dominicdeegan));
//		comics.add(new ComicInfo(context, R.raw.eightbittheater));
		comics.add(new ComicInfo(context, R.raw.girlgenius));
		comics.add(new ComicInfo(context, R.raw.girlswithslingshots));
		comics.add(new ComicInfo(context, R.raw.hipsterhitler));
		comics.add(new ComicInfo(context, R.raw.jesusandmo));
		comics.add(new ComicInfo(context, R.raw.kinokofry));
		comics.add(new ComicInfo(context, R.raw.leasticoulddo));
		comics.add(new ComicInfo(context, R.raw.lookingforgroup));
		comics.add(new ComicInfo(context, R.raw.megatokyo));
		comics.add(new ComicInfo(context, R.raw.misfile));
		comics.add(new ComicInfo(context, R.raw.moe));
		comics.add(new ComicInfo(context, R.raw.nedroid));
		comics.add(new ComicInfo(context, R.raw.pennyarcade));
		comics.add(new ComicInfo(context, R.raw.perrybiblefellowship));
		comics.add(new ComicInfo(context, R.raw.phdcomics));
		comics.add(new ComicInfo(context, R.raw.pvp));
		comics.add(new ComicInfo(context, R.raw.questionablecontent));
		comics.add(new ComicInfo(context, R.raw.sharkattack));
//		comics.add(new ComicInfo(context, R.raw.shockwatson));
		comics.add(new ComicInfo(context, R.raw.sinfest));
		comics.add(new ComicInfo(context, R.raw.smbc));
		comics.add(new ComicInfo(context, R.raw.starslip));
		comics.add(new ComicInfo(context, R.raw.userfriendly));
		comics.add(new ComicInfo(context, R.raw.vgcats));
		comics.add(new ComicInfo(context, R.raw.wondermark));
		comics.add(new ComicInfo(context, R.raw.xkcd));
		// These can't be parsed with the standard Downloader, on account of their lack of prev/next links
		comics.add(new ComicInfo("Married To The Sea", "http://www.marriedtothesea.com/", new Callable<Downloader>(){public Downloader call() throws Exception { return new SharingMachineDownloader("http://www.marriedtothesea.com"); }}));
		comics.add(new ComicInfo("Natalie Dee", "http://www.nataliedee.com/", new Callable<Downloader>(){public Downloader call() throws Exception { return new SharingMachineDownloader("http://www.nataliedee.com"); }}));
		comics.add(new ComicInfo("Toothpaste For Dinner", "http://www.toothpastefordinner.com/", new Callable<Downloader>(){public Downloader call() throws Exception { return new SharingMachineDownloader("http://www.toothpastefordinner.com"); }}));
		comics.add(new ComicInfo("Arctic Circle", "http://content.comicskingdom.net/Arctic/Arctic.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Arctic/Arctic.", false); }}));
		comics.add(new ComicInfo("DeFlocked", "http://content.comicskingdom.net/Deflocked/Deflocked.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Deflocked/Deflocked.", false); }}));
		comics.add(new ComicInfo("Flash Gordon", "http://content.comicskingdom.net/Flash/Flash.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Flash/Flash.", true); }}));
		comics.add(new ComicInfo("Hazel", "http://content.comicskingdom.net/Hazel/Hazel.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Hazel/Hazel.", false); }}));
		comics.add(new ComicInfo("Heaven's Love Thrift Shop", "http://content.comicskingdom.net/Heavens/Heavens.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Heavens/Heavens.", false); }}));
		comics.add(new ComicInfo("Henry", "http://content.comicskingdom.net/Henry/Henry.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Henry/Henry.", false); }}));
		comics.add(new ComicInfo("The Katzenjammer Kids", "http://content.comicskingdom.net/Katzenjammer_Kids/Katzenjammer_Kids.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Katzenjammer_Kids/Katzenjammer_Kids.", true); }}));
		comics.add(new ComicInfo("Mandrake the Magician", "http://content.comicskingdom.net/Mandrake/Mandrake.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Mandrake/Mandrake.", false); }}));
		comics.add(new ComicInfo("Oh, Brother!", "http://content.comicskingdom.net/Oh_Brother/Oh_Brother.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Oh_Brother/Oh_Brother.", false); }}));
		comics.add(new ComicInfo("Ollie and Quentin", "http://content.comicskingdom.net/Ollie/Ollie.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Ollie/Ollie.", false); }}));
		comics.add(new ComicInfo("On the Fastrack", "http://content.comicskingdom.net/Fast_Track/Fast_Track.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Fast_Track/Fast_Track.", false); }}));
		comics.add(new ComicInfo("The Pajama Diaries", "http://content.comicskingdom.net/Pajama/Pajama.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Pajama/Pajama.", false); }}));
		comics.add(new ComicInfo("Popeye", "http://content.comicskingdom.net/Popeye/Popeye.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Popeye/Popeye.", false); }}));
		comics.add(new ComicInfo("Prince Valiant", "http://content.comicskingdom.net/Prince_Valiant/Prince_Valiant.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Prince_Valiant/Prince_Valiant.", true); }}));
		comics.add(new ComicInfo("Pros & Cons", "http://content.comicskingdom.net/Lawyer/Lawyer.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Lawyer/Lawyer.", false); }}));
		comics.add(new ComicInfo("Retail", "http://content.comicskingdom.net/Retail/Retail.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Retail/Retail.", false); }}));
		comics.add(new ComicInfo("Sam and Silo", "http://content.comicskingdom.net/Sam/Sam.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Sam/Sam.", false); }}));
		comics.add(new ComicInfo("Tina's Groove", "http://content.comicskingdom.net/Tinas_Groove/Tinas_Groove.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Tinas_Groove/Tinas_Groove.", false); }}));
		comics.add(new ComicInfo("Todd the Dinosaur", "http://content.comicskingdom.net/Todd/Todd.", new Callable<Downloader>(){public Downloader call() throws Exception { return new ComicsKingdomDownloader("http://content.comicskingdom.net/Todd/Todd.", false); }}));
		
		comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "Archie", "http://www.creators.com/comics/archie.html"));
	   	comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "Ask Shagg", "http://www.creators.com/comics/ask-shagg.html"));
		comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "Flare", "http://www.creators.com/comics/flare.html"));
	   	comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "For Heaven's Sake", "http://www.creators.com/comics/for-heavens-sake.html"));
	   	comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "The Quigmans", "http://www.creators.com/comics/the-quigmans.html"));
	   	comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "Rugrats", "http://www.creators.com/comics/rugrats.html"));
	   	comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "State of the Union", "http://www.creators.com/comics/state-of-the-union.html"));
	   	comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "Thin Lines", "http://www.creators.com/comics/thin-lines.html"));
	   	comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "Wee Pals", "http://www.creators.com/comics/wee-pals.html"));
	   	comics.add(new ComicInfo(context, R.raw.creatorsdotcom, "Winnie the Pooh", "http://www.creators.com/comics/winnie-the-pooh.html"));
	   	comics.add(new ComicInfo(context, R.raw.arcamax, "The Boondocks", "http://www.arcamax.com/boondocks/"));
		comics.add(new ComicInfo(context, R.raw.arcamax, "Cathy", "http://www.arcamax.com/cathy/"));
		comics.add(new ComicInfo(context, R.raw.arcamax, "Jerry King Cartoons", "http://www.arcamax.com/humorcartoon/"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "2 Cows and a Chicken", "http://www.gocomics.com/2cowsandachicken"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "9 Chickweed Lane", "http://www.gocomics.com/9chickweedlane"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "9 to 5", "http://www.gocomics.com/9to5"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Academia Waltz", "http://www.gocomics.com/academiawaltz"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Adam@Home", "http://www.gocomics.com/adamathome"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Agnes", "http://www.gocomics.com/agnes"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Alley Oop", "http://www.gocomics.com/alley-oop"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Andy Capp", "http://www.gocomics.com/andycapp"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Animal Crackers", "http://www.gocomics.com/animalcrackers"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Argyle Sweater", "http://www.gocomics.com/theargylesweater"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Arlo and Janis", "http://www.gocomics.com/arloandjanis"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "B.C.", "http://www.gocomics.com/bc"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Back in the Day", "http://www.gocomics.com/backintheday"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Bad Reporter", "http://www.gocomics.com/badreporter"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Baldo", "http://www.gocomics.com/baldo"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Ballard Street", "http://www.gocomics.com/ballardstreet"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Barkeater Lake", "http://www.gocomics.com/barkeaterlake"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Barn", "http://www.gocomics.com/thebarn"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Barney & Clyde", "http://www.gocomics.com/barneyandclyde"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Basic Instructions", "http://www.gocomics.com/basicinstructions"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Ben", "http://www.gocomics.com/ben"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Betty", "http://www.gocomics.com/betty"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Bewley", "http://www.gocomics.com/bewley"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Big Nate", "http://www.gocomics.com/bignate"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Big Picture", "http://www.gocomics.com/thebigpicture"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Big Top", "http://www.gocomics.com/bigtop"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Biographic", "http://www.gocomics.com/biographic"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Birdbrains", "http://www.gocomics.com/birdbrains"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Bliss", "http://www.gocomics.com/bliss"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Bloom County", "http://www.gocomics.com/bloomcounty"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Bo Nanas", "http://www.gocomics.com/bonanas"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Bob the Squirrel", "http://www.gocomics.com/bobthesquirrel"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Boomerangs", "http://www.gocomics.com/boomerangs"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Born Loser", "http://www.gocomics.com/the-born-loser"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Bottomliners", "http://www.gocomics.com/bottomliners"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Bound and Gagged", "http://www.gocomics.com/boundandgagged"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Brainwaves", "http://www.gocomics.com/brainwaves"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Brevity", "http://www.gocomics.com/brevity"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Brewster Rockit", "http://www.gocomics.com/brewsterrockit"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Broom Hilda", "http://www.gocomics.com/broomhilda"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Buckets", "http://www.gocomics.com/thebuckets"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Caf con Leche", "http://www.gocomics.com/cafeconleche"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Calvin and Hobbes", "http://www.gocomics.com/calvinandhobbes"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Candorville", "http://www.gocomics.com/candorville"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "C'est la Vie", "http://www.gocomics.com/cestlavie"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Chuckle Bros", "http://www.gocomics.com/chucklebros"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Citizen Dog", "http://www.gocomics.com/citizendog"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The City", "http://www.gocomics.com/thecity"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Cleats", "http://www.gocomics.com/cleats"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Close to Home", "http://www.gocomics.com/closetohome"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Compu-toon", "http://www.gocomics.com/compu-toon"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Cornered", "http://www.gocomics.com/cornered"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Cow and Boy", "http://www.gocomics.com/cowandboy"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "CowTown", "http://www.gocomics.com/cowtown"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Cul de Sac", "http://www.gocomics.com/culdesac"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Daddy's Home", "http://www.gocomics.com/daddyshome"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Dark Side of the Horse", "http://www.gocomics.com/darksideofthehorse"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Deep Cover", "http://www.gocomics.com/deepcover"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Diamond Lil", "http://www.gocomics.com/diamondlil"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Dick Tracy", "http://www.gocomics.com/dicktracy"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Dinette Set", "http://www.gocomics.com/dinetteset"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Dog Eat Doug", "http://www.gocomics.com/dogeatdoug"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Dogs of C-Kennel", "http://www.gocomics.com/dogsofckennel"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Domestic Abuse", "http://www.gocomics.com/domesticabuse"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Doodles", "http://www.gocomics.com/doodles"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Doonesbury", "http://www.gocomics.com/doonesbury"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Doozies", "http://www.gocomics.com/thedoozies"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Drabble", "http://www.gocomics.com/drabble"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Dude and Dude", "http://www.gocomics.com/dudedude"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Duplex", "http://www.gocomics.com/duplex"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Eek!", "http://www.gocomics.com/eek"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Elderberries", "http://www.gocomics.com/theelderberries"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Endtown", "http://www.gocomics.com/endtown"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "F Minus", "http://www.gocomics.com/fminus"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Family Tree", "http://www.gocomics.com/familytree"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Ferd'nand", "http://www.gocomics.com/ferdnand"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Flo and Friends", "http://www.gocomics.com/floandfriends"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Flying McCoys", "http://www.gocomics.com/theflyingmccoys"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "For Better or For Worse", "http://www.gocomics.com/forbetterorforworse"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Fort Knox", "http://www.gocomics.com/fortknox"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "FoxTrot", "http://www.gocomics.com/foxtrot"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "FoxTrot Classics", "http://www.gocomics.com/foxtrotclassics"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Frank & Ernest", "http://www.gocomics.com/frankandernest"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Frazz", "http://www.gocomics.com/frazz"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Fred Basset", "http://www.gocomics.com/fredbasset"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Free Range", "http://www.gocomics.com/freerange"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Freshly Squeezed", "http://www.gocomics.com/freshlysqueezed"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Frog Applause", "http://www.gocomics.com/frogapplause"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Fusco Brothers", "http://www.gocomics.com/thefuscobrothers"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Garfield", "http://www.gocomics.com/garfield"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Garfield Minus Garfield", "http://www.gocomics.com/garfieldminusgarfield"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Gasoline Alley", "http://www.gocomics.com/gasolinealley"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Get a Life", "http://www.gocomics.com/getalife"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Get Fuzzy", "http://www.gocomics.com/getfuzzy"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Gil Thorp", "http://www.gocomics.com/gilthorp"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Ginger Meggs", "http://www.gocomics.com/gingermeggs"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Girls & Sports", "http://www.gocomics.com/girlsandsports"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Graffiti", "http://www.gocomics.com/graffiti"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Grand Avenue", "http://www.gocomics.com/grand-avenue"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Grizzwells", "http://www.gocomics.com/thegrizzwells"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Haiku Ewe", "http://www.gocomics.com/haikuewe"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Heart of the City", "http://www.gocomics.com/heartofthecity"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Heathcliff", "http://www.gocomics.com/heathcliff"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Herb and Jamaal", "http://www.gocomics.com/herbandjamaal"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Herman", "http://www.gocomics.com/herman"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Home and Away", "http://www.gocomics.com/homeandaway"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Hubert and Abby", "http://www.gocomics.com/hubertandabby"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Imagine This", "http://www.gocomics.com/imaginethis"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "In the Bleachers", "http://www.gocomics.com/inthebleachers"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "In the Sticks", "http://www.gocomics.com/inthesticks"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Incidental Comics", "http://www.gocomics.com/incidentalcomics"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Ink Pen", "http://www.gocomics.com/inkpen"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "It's All About You", "http://www.gocomics.com/itsallaboutyou"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Jane's World", "http://www.gocomics.com/janesworld"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Jim's Journal", "http://www.gocomics.com/jimsjournal"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Joe Vanilla", "http://www.gocomics.com/joevanilla"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Jump Start", "http://www.gocomics.com/jumpstart"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "KidSpot", "http://www.gocomics.com/kidspot"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Kit 'N' Carlyle", "http://www.gocomics.com/kitandcarlyle"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Knight Life", "http://www.gocomics.com/theknightlife"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "La Cucaracha", "http://www.gocomics.com/lacucaracha"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Last Kiss", "http://www.gocomics.com/lastkiss"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The LeftyBosco Picture Show", "http://www.gocomics.com/leftyboscopictureshow"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Legend of Bill", "http://www.gocomics.com/legendofbill"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Liberty Meadows", "http://www.gocomics.com/libertymeadows"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Lio", "http://www.gocomics.com/lio"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Little Dog Lost", "http://www.gocomics.com/littledoglost"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Lola", "http://www.gocomics.com/lola"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Loose Parts", "http://www.gocomics.com/looseparts"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Lost Side of Suburbia", "http://www.gocomics.com/lostsideofsuburbia"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Love Is...", "http://www.gocomics.com/loveis"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Luann", "http://www.gocomics.com/luann"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Lucky Cow", "http://www.gocomics.com/luckycow"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Maintaining", "http://www.gocomics.com/maintaining"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Marmaduke", "http://www.gocomics.com/marmaduke"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Meaning of Lila", "http://www.gocomics.com/meaningoflila"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Middletons", "http://www.gocomics.com/themiddletons"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Minimum Security", "http://www.gocomics.com/minimumsecurity"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Moderately Confused", "http://www.gocomics.com/moderately-confused"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Molly and the Bear", "http://www.gocomics.com/mollyandthebear"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Momma", "http://www.gocomics.com/momma"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Monty", "http://www.gocomics.com/monty"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Mutt & Jeff", "http://www.gocomics.com/muttandjeff"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "My Cage", "http://www.gocomics.com/mycage"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "MythTickle", "http://www.gocomics.com/mythtickle"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Nancy", "http://www.gocomics.com/nancy"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Nest Heads", "http://www.gocomics.com/nestheads"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "NEUROTICA", "http://www.gocomics.com/neurotica"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "New Adventures of Queen Victoria", "http://www.gocomics.com/thenewadventuresofqueenvictoria"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Non Sequitur", "http://www.gocomics.com/nonsequitur"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Norm", "http://www.gocomics.com/thenorm"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Off the Mark", "http://www.gocomics.com/offthemark"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "On A Claire Day", "http://www.gocomics.com/onaclaireday"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "One Big Happy", "http://www.gocomics.com/onebighappy"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "The Other Coast", "http://www.gocomics.com/theothercoast"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Out of the Gene Pool Re-Runs", "http://www.gocomics.com/outofthegenepool"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Over the Hedge", "http://www.gocomics.com/overthehedge"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Overboard", "http://www.gocomics.com/overboard"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "PC and Pixel", "http://www.gocomics.com/pcandpixel"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Peanuts", "http://www.gocomics.com/peanuts"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Pearls Before Swine", "http://www.gocomics.com/pearlsbeforeswine"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Pibgorn", "http://www.gocomics.com/pibgorn"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Pibgorn Sketches", "http://www.gocomics.com/pibgornsketches"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Pickles", "http://www.gocomics.com/pickles"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Pinkerton", "http://www.gocomics.com/pinkerton"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Pluggers", "http://www.gocomics.com/pluggers"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Pooch Caf", "http://www.gocomics.com/poochcafe"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "PreTeena", "http://www.gocomics.com/preteena"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Prickly City", "http://www.gocomics.com/pricklycity"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Rabbits Against Magic", "http://www.gocomics.com/rabbitsagainstmagic"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Real Life Adventures", "http://www.gocomics.com/reallifeadventures"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Reality Check", "http://www.gocomics.com/realitycheck"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Red and Rover", "http://www.gocomics.com/redandrover"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Red Meat", "http://www.gocomics.com/redmeat"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Reply All", "http://www.gocomics.com/replyall"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Reynolds Unwrapped", "http://www.gocomics.com/reynoldsunwrapped"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Rip Haywire", "http://www.gocomics.com/riphaywire"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Ripley's Believe It or Not", "http://www.gocomics.com/ripleysbelieveitornot"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Ronaldinho Gaucho", "http://www.gocomics.com/ronaldinhogaucho"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Rose is Rose", "http://www.gocomics.com/roseisrose"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Rubes", "http://www.gocomics.com/rubes"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Rudy Park", "http://www.gocomics.com/rudypark"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Scary Gary", "http://www.gocomics.com/scarygary"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Shoe", "http://www.gocomics.com/shoe"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Shoecabbage", "http://www.gocomics.com/shoecabbage"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Skin Horse", "http://www.gocomics.com/skinhorse"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Slowpoke", "http://www.gocomics.com/slowpoke"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Soup to Nutz", "http://www.gocomics.com/soup-to-nutz"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Speed Bump", "http://www.gocomics.com/speedbump"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Stone Soup", "http://www.gocomics.com/stonesoup"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Strange Brew", "http://www.gocomics.com/strangebrew"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Sylvia", "http://www.gocomics.com/sylvia"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Tank McNamara", "http://www.gocomics.com/tankmcnamara"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Tarzan", "http://www.gocomics.com/tarzan"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Thatababy", "http://www.gocomics.com/thatababy"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "(th)ink", "http://www.gocomics.com/think"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Tiny Sepuku", "http://www.gocomics.com/tinysepuku"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "TOBY", "http://www.gocomics.com/toby"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Today's Dogg", "http://www.gocomics.com/todays-dogg"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Tom the Dancing Bug", "http://www.gocomics.com/tomthedancingbug"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Too Much Coffee Man", "http://www.gocomics.com/toomuchcoffeeman"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Unstrange Phenomena", "http://www.gocomics.com/unstrange-phenomena"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Watch Your Head", "http://www.gocomics.com/watchyourhead"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Wizard of Id", "http://www.gocomics.com/wizardofid"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Working Daze", "http://www.gocomics.com/working-daze"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Working It Out", "http://www.gocomics.com/workingitout"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "W.T. Duck", "http://www.gocomics.com/wtduck"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Yenny", "http://www.gocomics.com/yenny"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Zack Hill", "http://www.gocomics.com/zackhill"));
		comics.add(new ComicInfo(context, R.raw.gocomics, "Ziggy", "http://www.gocomics.com/ziggy"));
		
		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Apartment 3-G", "http://www.chron.com/apps/comics/buildcp.mpl?c=100&page=1&cpp=1&v=3.0&quality=high"));
		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Between Friends", "http://www.chron.com/apps/comics/buildcp.mpl?c=143&page=1&cpp=1&v=3.0&quality=high"));
		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Crock", "http://www.chron.com/apps/comics/buildcp.mpl?c=106&page=1&cpp=1&v=3.0&quality=high"));
		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Mark Trail", "http://www.chron.com/apps/comics/buildcp.mpl?c=144&page=1&cpp=1&v=3.0&quality=high"));
		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Redeye", "http://www.chron.com/apps/comics/buildcp.mpl?c=126&page=1&cpp=1&v=3.0&quality=high"));
		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Tiger", "http://www.chron.com/apps/comics/buildcp.mpl?c=132&page=1&cpp=1&v=3.0&quality=high"));
		// For reasons that are unclear, these 3 comics fail to load
		//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Boffo", "http://www.chron.com/apps/comics/buildcp.mpl?c=12&page=1&cpp=1&v=3.0&quality=high"));
		//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Prickly City", "http://www.chron.com/apps/comics/buildcp.mpl?c=92&page=1&cpp=1&v=3.0&quality=high"));
		//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Willy & Ethel", "http://www.chron.com/apps/comics/buildcp.mpl?c=77&page=1&cpp=1&v=3.0&quality=high"));

		
		/**
		 * King Syndicate Comics
		 */
//	   	comics.add(new ComicInfo(context, R.raw.arcamax, "Baby Blues", "http://www.arcamax.com/babyblues/"));
//		comics.add(new ComicInfo(context, R.raw.arcamax, "Beetle Bailey", "http://www.arcamax.com/beetlebailey/"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Better Half", "http://www.chron.com/apps/comics/buildcp.mpl?c=103&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Bizarro", "http://www.chron.com/apps/comics/buildcp.mpl?c=153&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.gocomics, "Bleeker: The Rechargeable Dog", "http://www.gocomics.com/bleeker"));
//		comics.add(new ComicInfo(context, R.raw.arcamax, "Blondie", "http://www.arcamax.com/blondie/"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "The Brilliant Mind of Edison Lee", "http://www.chron.com/apps/comics/buildcp.mpl?c=156&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Buckles", "http://www.chron.com/apps/comics/buildcp.mpl?c=105&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Crankshaft", "http://www.chron.com/apps/comics/buildcp.mpl?c=154&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Curtis", "http://www.chron.com/apps/comics/buildcp.mpl?c=107&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Dennis the Menace", "http://www.chron.com/apps/comics/buildcp.mpl?c=108&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.arcamax, "Dustin", "http://www.arcamax.com/dustin/"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Edge City", "http://www.chron.com/apps/comics/buildcp.mpl?c=151&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Fast Track", "http://www.chron.com/apps/comics/buildcp.mpl?c=111&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.arcamax, "Family Circus", "http://www.arcamax.com/familycircus/"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Funky Winkerbean", "http://www.chron.com/apps/comics/buildcp.mpl?c=112&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Grin and Bear It", "http://www.chron.com/apps/comics/buildcp.mpl?c=113&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.arcamax, "Hagar the Horrible", "http://www.arcamax.com/hagarthehorrible/"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Hi & Lois", "http://www.chron.com/apps/comics/buildcp.mpl?c=115&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Judge Parker", "http://www.chron.com/apps/comics/buildcp.mpl?c=116&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Lockhorns", "http://www.chron.com/apps/comics/buildcp.mpl?c=117&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Mallard Fillmore", "http://www.chron.com/apps/comics/buildcp.mpl?c=118&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Marvin", "http://www.chron.com/apps/comics/buildcp.mpl?c=119&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Mary Worth", "http://www.chron.com/apps/comics/buildcp.mpl?c=120&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.arcamax, "Mother Goose & Grimm", "http://www.arcamax.com/mothergooseandgrimm/"));
//		comics.add(new ComicInfo(context, R.raw.arcamax, "Mutts", "http://www.arcamax.com/mutts/"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "My Cage", "http://www.chron.com/apps/comics/buildcp.mpl?c=157&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Pardon My Planet", "http://www.chron.com/apps/comics/buildcp.mpl?c=152&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Phantom", "http://www.chron.com/apps/comics/buildcp.mpl?c=123&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Piranha Club", "http://www.chron.com/apps/comics/buildcp.mpl?c=124&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Rex Morgan", "http://www.chron.com/apps/comics/buildcp.mpl?c=127&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Rhymes with Orange", "http://www.chron.com/apps/comics/buildcp.mpl?c=136&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Safe Havens", "http://www.chron.com/apps/comics/buildcp.mpl?c=128&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Sally Forth", "http://www.chron.com/apps/comics/buildcp.mpl?c=129&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.shermanslagoon));
//		comics.add(new ComicInfo(context, R.raw.gocomics, "Shoe", "http://www.gocomics.com/shoe"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Six Chix", "http://www.chron.com/apps/comics/buildcp.mpl?c=147&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Slylock Fox", "http://www.chron.com/apps/comics/buildcp.mpl?c=146&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Snuffy Smith", "http://www.chron.com/apps/comics/buildcp.mpl?c=148&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Spider-Man", "http://www.chron.com/apps/comics/buildcp.mpl?c=130&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.houstonchronicle, "Zippy the Pinhead", "http://www.chron.com/apps/comics/buildcp.mpl?c=137&page=1&cpp=1&v=3.0&quality=high"));
//		comics.add(new ComicInfo(context, R.raw.arcamax, "Zits", "http://www.arcamax.com/zits/"));
		
		Collections.sort(comics);
	}
}
